[book]
title = "The Erigon 3 book"
authors = ["Gianni Morselli"]
description = "Erigon 3 documentation!"
language = "en"
multilingual = false
src = "src"
# [output.html]
# additional-css = ["theme/css/variables.css"]
# template-path = "theme"